BASE: "../mmm_panoptic_deeplab_pointrend.yaml"

DATASET:
  dataset_name: "MitoMegaMix_CopyPaste"

TRAIN:
  augmentations:
    - { aug: "PadIfNeeded", min_height: 256, min_width: 256, border_mode: 0 }
    - { aug: "RandomResizedCrop", height: 256, width: 256, scale: [ 0.2, 1.0 ], ratio: [ 0.5, 1.5 ] }
    - { aug: "Rotate", limit: 180, border_mode: 0 }
    - { aug: "RandomBrightnessContrast", brightness_limit: 0.1, contrast_limit: 0.1 }
    - { aug: "CopyPaste", blend: True, sigma: 1, pct_objects_paste: 0.8, p: 0.8 }
    - { aug: "HorizontalFlip" }
    - { aug: "VerticalFlip" }