BASE: "./epochs50_base.yaml"

TRAIN:
  model_dir: "/data/IASEM/conradrw/models/PDPR_epoch50_fixed_lr"
  save_freq: 1

  optimizer: "AdamW"
  optimizer_params:
    lr: 0.001
  
  # set the lr schedule
  epochs: 50
  lr_schedule: "StepLR"
  schedule_params:
    step_size: 50