BASE: "./epochs50_base.yaml"
    
MODEL:
  arch: "PanopticDeepLabPR"
  encoder: "resnet50" 
  low_level_stages: [ 1 ]
  low_level_channels_project: [ 32 ]
  ins_decoder: True
  ins_ratio: 0.5

TRAIN:
  model_dir: "/data/IASEM/conradrw/models/PDPR_epoch50_sparse_decoder"