BASE: "./epochs50_base.yaml"

TRAIN:
  model_dir: "/data/IASEM/conradrw/models/PDPR_epoch50_augs"
  save_freq: 1
  
  resume: "/data/IASEM/conradrw/models/PDPR_epoch50_augs/epochs50_augs_checkpoint.pth.tar"
  
  augmentations:
    - { aug: "RandomScale", scale_limit: [ -0.5, 1 ]}
    - { aug: "PadIfNeeded", min_height: 256, min_width: 256, border_mode: 0 }
    - { aug: "RandomGamma", gamma_limit: [ 80., 200. ]}
    - { aug: "GaussNoise", var_limit: [ 40., 200. ]}
    - { aug: "GaussianBlur", blur_limit: [ 3, 7 ]}
    - { aug: "RandomBrightnessContrast", brightness_limit: 0.3, contrast_limit: 0.3, p: 0.75 }
    - { aug: "PiecewiseAffine", p: 0.3}
    - { aug: "RandomCrop", height: 256, width: 256 }
    - { aug: "Rotate", limit: 180, border_mode: 0 }
    - { aug: "HorizontalFlip" }
    - { aug: "VerticalFlip" }