BASE: "../mmm_panoptic_deeplab_pointrend.yaml"

DATASET:
  dataset_name: "MitoMegaMix_PreBatch4b"

TRAIN:
  # image and model directories
  additional_train_dirs:
    - "/data/IASEM/conradrw/data/panoptic/zooniverse_staging/batch0/train"
    - "/data/IASEM/conradrw/data/panoptic/zooniverse_staging/batch1/train"
    - "/data/IASEM/conradrw/data/panoptic/zooniverse_staging/batch2a/train"
    - "/data/IASEM/conradrw/data/panoptic/zooniverse_staging/batch2b/train"
    - "/data/IASEM/conradrw/data/panoptic/zooniverse_staging/batch3a/train"
    - "/data/IASEM/conradrw/data/panoptic/zooniverse_staging/batch3b/train"
    - "/data/IASEM/conradrw/data/panoptic/zooniverse_staging/batch4a/train"
    
  model_dir: "/data/IASEM/conradrw/models/MMM_Panoptic_DeepLab_PointRend_ZB4b"
  
EVAL:
  eval_dir: "/data/IASEM/conradrw/data/panoptic/zooniverse_staging/batch4b/train"
  eval_track_indices: null