BASE: "../mmm_panoptic_deeplab_pointrend.yaml"

DATASET:
  dataset_name: "MitoMegaMix_PreBatch1"

TRAIN:
  # image and model directories
  additional_train_dirs:
    - "/data/IASEM/conradrw/data/panoptic/zooniverse_staging/batch0/train"
    
  model_dir: "/data/IASEM/conradrw/models/MMM_Panoptic_DeepLab_PointRend_ZB1"
  
EVAL:
  eval_dir: "/data/IASEM/conradrw/data/panoptic/zooniverse_staging/batch1/train"
  eval_track_indices: null