DATASET:
  dataset_name: "mito"
  data_dir: "/data/IASEM/conradrw/data/benchmarks/weigert/flipbooks/"
  model_dir: "/data/IASEM/conradrw/data/benchmarks/weigert/models/"
  class_names: 
    - "mito"
  norms:
    mean: 0.508982
    std: 0.148503
    
MODEL:
  arch: "PanopticRegFPNX"
  encoder: "resnet50" 
  #encoder: "regnety_6p4gf"
  num_classes: 1
  fpn_dim: 128
  fpn_layers: 3
  qt_layers: 1
  qt_heads: 8
  queue_len: 5
  target_index: 2
  attn_pdrop: 0.1
  resid_pdrop: 0.1
  ins_decoder: False

TRAIN:
  pretraining: "/data/IASEM/conradrw/models/pretrained_models/cem500k_mocov2_resnet50_200ep.pth.tar"
  finetune_layer: "none"
  unfreeze_encoder_bn: False
  n_processes: 8
  batch_size: 16
  lr: 0.003
  wd: 0.1
  momentum: 0.9
  optim: "AdamW"
  lr_policy: "OneCycle"
  iters: 5000
  
  # dataset weight gamma
  
  augmentations:
    - aug: "PadIfNeeded"
      min_height: 256
      min_width: 256
    - aug: "RandomResizedCrop"
      height: 256
      width: 256
      scale:
        - 0.08
        - 1.0
      ratio:
        - 0.5
        - 1.5
    - aug: "Rotate"
      limit: 180
    - aug: "RandomBrightnessContrast"
      brightness_limit: 0.1
      contrast_limit: 0.1
    - aug: "HorizontalFlip"
    - aug: "VerticalFlip"
  
  # path to .pth file for resuming training
  resume: ""
  num_save_checkpoints: 5
  logging: True
  metrics:
    - "IoU"
  num_prints: 10
  
INFERENCE:
  weight_path: "/data/IASEM/conradrw/data/benchmarks/weigert/models/PanopticRegFPNX_ft_none_OneCycle_5000.pth"
  engine_params:
    thing_list:
      - 1
    label_divisor: 1
    stuff_area: 64
    void_label: 0
    nms_threshold: 0.1
    nms_kernel: 7
    confidence_thr: 0.5
  matcher_params:
    merge_iou_thr: 0.25
    merge_ioa_thr: 0.25