DATASET:
  dataset_name: "MitoMegaMix"
  class_names: [ "mito" ]
  norms: { mean: 0.508979, std: 0.148561 }
    
MODEL:
  arch: "PanopticDeepLab"
  encoder: "resnet50" 
  num_classes: 1
  stage4_stride: 16
  decoder_channels: 256
  low_level_stages: [ 1 ]
  low_level_channels_project: [ 32 ]
  atrous_rates: [ 2, 4, 6 ]
  aspp_channels: null
  ins_decoder: True
  confidence_head: False
  confidence_bins: 5

TRAIN:
  # image and model directories
  train_dir: "/data/IASEM/conradrw/data/panoptic/train"
  model_dir: "/data/IASEM/conradrw/models/MMM_Panoptic_DeepLab"
  
  # path to .pth file for resuming training
  resume: null
  
  # pretraining parameters
  pretraining: "/data/IASEM/conradrw/models/pretrained_models/cem1.5m_swav_resnet50_200ep.pth.tar"
  finetune_layer: "all"
  
  # set the lr schedule
  lr_schedule: "OneCycleLR"
  schedule_params:
    max_lr: 0.003
    epochs: 100
    steps_per_epoch: 314
    pct_start: 0.2

  # setup the optimizer
  amp: True  # automatic mixed precision
  optimizer: "AdamW"
  optimizer_params:
    weight_decay: 0.1
    
  # criterion parameters
  criterion_params:
    ce_weight: 1
    mse_weight: 200
    l1_weight: 0.01
    top_k_percent: 0.2
    confidence_loss: False
    cl_weight: 0.1

  # performance metrics
  print_freq: 50
  metrics: [ "IoU" ]
  metric_params:
    topk: 1
    
  # dataset parameters
  batch_size: 64
  weight_gamma: 0.75
  workers: 8
  
  augmentations:
    - { aug: "PadIfNeeded", min_height: 256, min_width: 256, border_mode: 0 }
    - { aug: "RandomResizedCrop", height: 256, width: 256, scale: [ 0.08, 1.0 ], ratio: [ 0.5, 1.5 ] }
    - { aug: "Rotate", limit: 180, border_mode: 0 }
    - { aug: "RandomBrightnessContrast", brightness_limit: 0.1, contrast_limit: 0.1 }
    - { aug: "HorizontalFlip" }
    - { aug: "VerticalFlip" }

  # distributed training parameters
  multiprocessing_distributed: False
  gpu: null
  world_size: 1
  rank: 0
  dist_url: "tcp://localhost:10001"
  dist_backend: "nccl"
  
EVAL:
  eval_dir: "/data/IASEM/conradrw/data/panoptic/eval"
  eval_track_indices: [ 0, 19, 23, 35, 40, 33, 10, 7 ] # from batch3a gt
  eval_track_freq: 5
  
  # parameters needed for eval_metrics
  metrics: [ "IoU", "PQ" ]
  metric_params:
      topk: 1
      labels: [ 1 ]
      label_divisor: 1000
  
  # parameters needed for inference
  engine_params:
    thing_list: [ 1 ]
    label_divisor: 1000
    stuff_area: 64
    void_label: 0
    nms_threshold: 0.1
    nms_kernel: 7
    confidence_thr: 0.5