dataset_name: "Baselines"

MODEL:
  config: "/data/conradrw/mitonet_bifpn/PanopticBiFPNPR_mitonet_bifpn_120.yaml"

TRAIN:
  run_name: "Finetune testing BiFPN"
  
  train_dir: "/data/IASEM/conradrw/data/panoptic/hari_ft/"
  additional_train_dirs: null

  model_dir: "/data/IASEM/conradrw/models/finetuning"
  save_freq: 10

  # path to .pth file for resuming training
  resume: null

  finetune_layer: "none"

  # set the lr schedule
  lr_schedule: "OneCycleLR"
  schedule_params:
    max_lr: 0.003
    epochs: 100
    steps_per_epoch: -1
    pct_start: 0.3

  # setup the optimizer
  amp: True  # automatic mixed precision
  optimizer: "AdamW"
  optimizer_params:
    weight_decay: 0.1

  # performance metrics
  print_freq: 50
  metrics:
      - { metric: "IoU", name: "semantic_iou", labels: [ 1 ], output_key: "sem_logits",  target_key: "sem"}

  # dataset parameters
  batch_size: 16
  workers: 4
  
  augmentations:
    - { aug: "RandomScale", scale_limit: [ -0.9, 1 ]}
    - { aug: "PadIfNeeded", min_height: 256, min_width: 256, border_mode: 0 }
    - { aug: "RandomCrop", height: 256, width: 256}
    - { aug: "Rotate", limit: 180, border_mode: 0 }
    - { aug: "RandomBrightnessContrast", brightness_limit: 0.3, contrast_limit: 0.3 }
    - { aug: "HorizontalFlip" }
    - { aug: "VerticalFlip" }

EVAL:
  eval_dir: "/data/IASEM/conradrw/data/panoptic/hari_ft/"
  eval_track_indices: null
  eval_track_freq: 10
  epochs_per_eval: 10

  # parameters needed for eval_metrics
  metrics:
      - { metric: "IoU", name: "semantic_iou", labels: [ 1 ], output_key: "sem_logits",  target_key: "sem"}
      - { metric: "PQ", name: "pq", labels: [ 1 ], label_divisor: 1000, output_key: "pan_seg",  target_key: "pan_seg"}
      - { metric: "F1", name: "f1_50", labels: [ 1 ], label_divisor: 1000, iou_thr: 0.5, output_key: "pan_seg",  target_key: "pan_seg"}
