BASE: "./mmm_median_inference.yaml"
  
# parameters for the inference engine
engine_params:
  median_kernel_size: 3
  confidence_thr: 0.3
  
consensus_params:
  pixel_vote_thr: 0.25
  cluster_iou_thr: 0.75
  min_iou: 0.1
  min_overlap_area: 500

# simple object size/shape filters
filters:
  - { name: "remove_small_objects", min_size: 500 }
  - { name: "remove_pancakes", min_span: 8 }