BASE: "./mmm_panoptic_bifpn_pointrend.yaml"

DATASET:
  dataset_name: "MitoMegaMix_BiFPNPR_Mini"
    
MODEL:
  arch: "PanopticBiFPNPR"
  encoder: "regnety_800mf"
  fpn_dim: 128
  fpn_layers: 3

TRAIN:
  model_dir: "/data/IASEM/conradrw/models/MMM_Panoptic_BiFPNPR_Mini"
  
  # pretraining parameters
  encoder_pretraining: null
  whole_pretraining: null
  finetune_layer: "all"
  
  # set the lr schedule
  lr_schedule: "OneCycleLR"
  schedule_params:
    max_lr: 0.001
    epochs: 30
    steps_per_epoch: 332
    pct_start: 0.3

  # setup the optimizer
  amp: True  # automatic mixed precision
  optimizer: "AdamW"
  optimizer_params:
    weight_decay: 0.01
