BASE: "./mmm_median_inference.yaml"

axes: [ 'xy', 'xz', 'yz' ]

# parameters for the inference engine
engine_params:
  median_kernel_size: 3

# simple object size/shape filters
filters:
  - { name: "remove_small_objects", min_size: 500 }
  - { name: "remove_pancakes", min_span: 4 }