BASE: "./mmm_panoptic_deeplab_pointrend.yaml"

MODEL:
  arch: "PanopticBiFPNPR"
  encoder: "resnet50"
  num_classes: 1
  fpn_dim: 128
  fpn_layers: 3
  ins_decoder: True
  confidence_head: False
  confidence_bins: 5
  depthwise: True

