# axes to predict for 3d
axes: [ 'xy', 'xz', 'yz' ]

# list of all segmentation labels
labels: [ 1 ]

# parameters for the inference engine
engine_params:
  median_kernel_size: 3

watershed_params:
  thres1: 0.9
  thres2: 0.5
  thres3: 0.5
  seed_thres: 32
  min_size: 128
  label_divisor: 1000

