BASE: "./batch4_epochs50_base.yaml"

DATASET:
  dataset_name: "HPO_Up_To_Batch3b"

MODEL:
  arch: "PanopticDeepLabPR"
  encoder: "resnet50" 
  low_level_stages: [ 1 ]
  low_level_channels_project: [ 32 ]
  ins_decoder: True
  ins_ratio: 0.5

TRAIN:
  model_dir: "/data/IASEM/conradrw/models/PDPR_epoch50_batch4b_crop480"
  save_freq: 1
  
  batch_size: 16
  
  # set the lr schedule
  lr_schedule: "OneCycleLR"
  schedule_params:
    max_lr: 0.003
    epochs: 50
    steps_per_epoch: 1297
    pct_start: 0.3
  
  augmentations:
    - { aug: "RandomScale", scale_limit: [ -0.5, 1 ]}
    - { aug: "PadIfNeeded", min_height: 480, min_width: 480, border_mode: 0 }
    #- { aug: "RandomResizedCrop", height: 256, width: 256, scale: [ 0.5, 2 ], ratio: [ 0.8, 1.2 ] }
    - { aug: "RandomCrop", height: 480, width: 480}
    - { aug: "Rotate", limit: 180, border_mode: 0 }
    - { aug: "RandomBrightnessContrast", brightness_limit: 0.2, contrast_limit: 0.2 }
    - { aug: "HorizontalFlip" }
    - { aug: "VerticalFlip" }