name: deploy 

on: 
  push:
    branches: [ main ]
    tags: [ "v*" ]
  pull_request:
    branches: [ main ] 

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: contains(github.ref, 'tags')

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U setuptools setuptools_scm wheel twine

      - name: Build and Upload to PyPi
        run: |
          git tag
          python setup.py sdist bdist_wheel
          python -m twine upload dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TWINE_API_KEY }}
